# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'iOSLangUseDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'iOSLang', '1.0.0'

  install_all_flutter_pods(flutter_application_path)

end

